### ISSUE TITLE
How can I cancel it? 

### ISSUE THREAD

**Issue by lexluthors** [JasonLG1979/gnome-shell-extension-skip-window-ready-notification#1] opened 2021-01-13 07:39 UTC
How can I cancel it? The notification still pops up automatically after I close it

**Comment by JasonLG1979** [comment] 2021-01-15 18:30
Cancel what? I guess I don't understand what you mean? With this extension enabled you should never see a notification that a window is ready, the window in question should just take focus.

If you look at the code all it does is monkey patch the handler function that is called when a window requests focus and skips the notification bit.

**Comment by JasonLG1979** [comment] 2021-01-15 18:31
Cancel what? I guess I don't understand what you mean? With this extension enabled you should never see a notification that a window is ready, the window in question should just take focus.

**Comment by lexluthors** [comment] 2021-01-20 12:30
@JasonLG1979 I want to return to the state before the extension was enabled. The current situation is that my message window often pops up automatically when I type, which prevents me from typing normally. Regret to use the extension, I closed the extension in the extension management, but it did not take effect.

**Comment by JasonLG1979** [comment] 2021-01-20 15:39
Just disabling the the extension should work. If that for some reason doesn't revert things to the default behavior then restart the shell by logging out and back in. If all else fails completely remove the extension and reboot.

**Comment by lexluthors** [comment] 2021-01-21 07:31
@JasonLG1979 I deleted this extension and the window still pops up automatically after restarting the computer. I don't know how to turn off this plugin.

**Comment by JasonLG1979** [comment] 2021-01-21 14:25
What window? If you deleted the extension then it's not the extension that's causing you the problem.

**Comment by JasonLG1979** [comment] 2021-01-21 14:27
Extensions don't irrevocably change the Shell's code. They load after the Shell. If an extension is deleted then it's the same as if it were never there.

**Comment by JasonLG1979** [comment] 2021-01-23 05:04
So to recap. This is clearly not my bug. If the extension is uninstalled and the system rebooted the now nonexistent extension can not be the cause of your issues.

I'm closing this issue.

**Closed as completed by JasonLG1979** 2021-01-23 05:04 UTC
